[package]
name = "rustsftp"
version = "0.1.0"
authors = ["Louis VENTRE <oxydros@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.0.1"